---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: grakn
spec:
  selector:
    matchLabels:
      app: grakn # has to match .spec.template.metadata.labels
  serviceName: grakn
  replicas: 1
  template:
    metadata:
      labels:
        app: grakn
    spec:
      containers:
        - name: grakn
          image: graknlabs/grakn
          imagePullPolicy: IfNotPresent
          #image: grakn-1.0.0
          #imagePullPolicy: Never
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: STORAGE_SEEDS
              value: "grakn-0.grakn.default.svc.cluster.local"
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
