---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: grakn
spec:
  selector:
    matchLabels:
      app: grakn # has to match .spec.template.metadata.labels
  serviceName: grakn
  replicas: 2
  template:
    metadata:
      labels:
        app: grakn
    spec:
      containers:
        - name: grakn
          image: graknlabs/grakn
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: STORAGE_SEEDS
              value: "grakn-0.grakn.default.svc.cluster.local"
            - name: STORAGE_CLUSTER_NAME
              value: "Grakn Cluster"
           # - name: STORAGE_ENDPOINT_SNITCH
           #   value: GossipingPropertyFileSnitch
